# Permalinks
permalink:            pretty
relative_permalinks:  false

# Setup
title:            andfinally
tagline:
url:              http://andfinally.github.io
paginate:         1
baseurl:          /

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/andfinally.github.io
